spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  jackson:
    deserialization:
      fail-on-unknown-properties : true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 62101851974-a0h2cac880lj2nctm08gnm6s4rbru516.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 804885737295372
            client-secret: 28ac75f1440b3d1eef55df1b4e5608d0
            scope:
              - email
              - public_profile


logging:
  level:
    org:
      springframework.security: DEBUG
      hibernate.SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE

my-app:
  password: 123
  admin-username: admin
  manager-username: manager
  user-username: user
  email: temp@temp.temp

